apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  labels:
    app: nextcloud
type: Opaque
stringData:
  NEXTCLOUD_ADMIN_PASSWORD: "abobus"
  NEXTCLOUD_UPDATE: "1"
  ALLOW_EMPTY_PASSWORD: "yes"
  POSTGRES_HOST: postgres-service
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: "abobus"
  NEXTCLOUD_TRUSTED_DOMAINS: "127.0.0.1"