kind: Deployment
apiVersion: apps/v1
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: docker.io/nextcloud:stable-apache
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: nextcloud-configmap
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: nextcloud-secret

          livenessProbe:
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            
          readinessProbe:
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
          imagePullPolicy: IfNotPresent

      restartPolicy: Always
      dnsPolicy: ClusterFirst